Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/lightspeed_restaurant.rb'
    - 'lib/lightspeed_restaurant/errors/lightspeed_restaurant_error.rb'
    - 'lib/lightspeed_restaurant/version.rb'
